const presets = {
  css: {
    keywords: [
      'body',
      'html',
      'div',
      'span',
      'main',
      'section',
      'article',
      'header',
      'footer',
      '@media',
      '@import',
      '@keyframes',
      '@font-face',
      '@supports',
      '@charset',
      'margin',
      'padding',
      'border',
      'color',
      'background',
      'font-size',
      'width',
      'height',
      'display',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'flex',
      'grid',
      'important',
      'text-align',
      'line-height',
      'overflow',
      'z-index',
      'opacity'
    ],
    punctuation: ['{', '}', '(', ')', '[', ']', ';', ',', '.', ':', '*'],
    operators: ['>', '+', '~', '=', '<=', '>='],
    commentPrefixes: ['/*'],
    commentSuffixes: ['*/'],
    custom: {
      'css-value': [
        'red',
        'yellow',
        'green',
        'blue',
        'black',
        'white',
        'transparent',
        'inline',
        'block',
        'flex',
        'inline-flex',
        'grid',
        'none',
        'auto',
        'fixed',
        'absolute',
        'relative',
        'sticky',
        'inherit',
        'center',
        'left',
        'right',
        'justify',
        'solid',
        'dashed',
        'dotted',
        /var\(--[a-zA-Z0-9-]+\)/,
        /rgba?\([^)]+\)/,
        /hsla?\([^)]+\)/,
        /#[0-9a-fA-F]{3,8}/,
        /\d+px|\d+em|\d+rem|\d+%|\d+vh|\d+vw/
      ],
      variable: [/--[a-zA-Z0-9-]+/],
      selector: [
        /\.[a-zA-Z][\w-]*/,
        /#[a-zA-Z][\w-]*/,
        /\[[^\]]+\]/,
        /::[a-zA-Z-]+/,
        /:[a-zA-Z-]+/
      ],
      'at-rule': [/@[a-zA-Z-]+/]
    }
  },
  javascript: {
    keywords: [
      'function',
      'const',
      'let',
      'var',
      'if',
      'else',
      'for',
      'while',
      'do',
      'return',
      'break',
      'continue',
      'switch',
      'case',
      'default',
      'try',
      'catch',
      'finally',
      'throw',
      'class',
      'extends',
      'implements',
      'new',
      'this',
      'super',
      'import',
      'export',
      'from',
      'as',
      'async',
      'await',
      'yield',
      'typeof',
      'instanceof',
      'in',
      'of',
      'delete',
      'void',
      'debugger'
    ],
    punctuation: ['{', '}', '(', ')', '[', ']', ';', ',', '.', ':', '?'],
    operators: [
      '+',
      '-',
      '*',
      '/',
      '%',
      '**',
      '=',
      '+=',
      '-=',
      '*=',
      '/=',
      '%=',
      '**=',
      '==',
      '===',
      '!=',
      '!==',
      '>',
      '<',
      '>=',
      '<=',
      '&&',
      '||',
      '!',
      '??',
      '?.',
      '&',
      '|',
      '^',
      '~',
      '<<',
      '>>',
      '>>>',
      '++',
      '--',
      '=>'
    ],
    commentPrefixes: ['//', '/*'],
    commentSuffixes: ['', '*/'],
    custom: {
      boolean: ['true', 'false'],
      null: ['null', 'undefined'],
      global: [
        'window',
        'document',
        'console',
        'Math',
        'css',
        'Array',
        'Object',
        'String',
        'Number',
        'Boolean',
        'Date',
        'RegExp',
        'Map',
        'Set',
        'Promise',
        'JSON',
        'Error'
      ],
      regex: [/\/(?![\/\*])[^\n\/]*\/[gimuy]*/],
      template: [/\$\{[^}]*\}/]
    }
  },
  html: {
    keywords: [
      'html',
      'head',
      'body',
      'div',
      'span',
      'p',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'a',
      'img',
      'ul',
      'ol',
      'li',
      'table',
      'tr',
      'td',
      'th',
      'form',
      'input',
      'button',
      'select',
      'option',
      'textarea',
      'header',
      'footer',
      'nav',
      'main',
      'section',
      'article',
      'aside',
      'script',
      'style',
      'meta',
      'link',
      'title',
      'br',
      'hr',
      'iframe',
      'canvas'
    ],
    punctuation: ['<', '>', '/', '=', '"', "'", '`'],
    commentPrefixes: ['<!--'],
    commentSuffixes: ['-->'],
    custom: {
      attribute: [
        'id',
        'class',
        'style',
        'href',
        'src',
        'alt',
        'width',
        'height',
        'type',
        'value',
        'name',
        'placeholder',
        'disabled',
        'required',
        'checked',
        'selected',
        'readonly',
        'maxlength',
        'min',
        'max',
        'target',
        'rel',
        'onclick',
        'onchange',
        'onsubmit',
        'onload',
        'lang',
        'charset',
        'content',
        'method',
        'action'
      ],
      tag: [/<\/?[a-zA-Z][a-zA-Z0-9]*/, />/],
      entity: [/&[a-zA-Z0-9#]+;/]
    }
  }
}
